import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavMenuBar from "./components/NavMenuBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next Appdd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 bg-white z-10 border-b">
          <div className="max-w-screen-xl mx-auto">
            <NavMenuBar />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
