// 전체 레이아웃을 정의 및 공통부분 처리
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavMenuBar from "./components/NavMenuBar";
import RQProvider from "./components/RQProvider";
import TopBar from "./components/TopBar";
import AuthSession from "./components/common/AuthSessionCom";
import Advertisement from "./components/common/Advertisement";
import MessageView from "./components/common/MessageView";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS, NestJS 게시판",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RQProvider>
          <AuthSession>
            <div style={{ width: 1600, margin: "0 auto", padding: "0 20px" }}>
              {/* 상단 바 */}
              {/* TopBar의 높이와 동일하게 설정 */}
              <TopBar />
              {/* 아래걸로 하면 전체스크롤 */}
              {/* <div style={{ display: "flex", overflow: "hidden" }}> */}
              <div style={{ display: "flex", height: "calc(100vh - 60px)", overflow: "hidden" }}>
                {/* 왼쪽 네비게이션 */}
                <NavMenuBar />
                {/* 메인 콘텐츠: 중앙 정렬 */}
                <div style={{ flexGrow: 1, paddingLeft: "3px", width: 1250, overflowY: "auto" }}>{children}</div>
                <div style={{ width: 200 }}>
                  <Advertisement />
                </div>
                {/* 전역 메세지 표시 설정 */}
                <MessageView />
              </div>
            </div>
          </AuthSession>
        </RQProvider>
      </body>
    </html>
  );
}
