// 전체 레이아웃을 정의 및 공통부분 처리
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavMenuBar from "./components/NavMenuBar";
import RQProvider from "./components/RQProvider";
import TopBar from "./components/TopBar";
import AuthSession from "./components/common/AuthSessionCom";
import MessageView from "./components/common/MessageView";
import RightView from "./components/common/rightView";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS, NestJS 게시판",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 이거 alwaysScroll이라는 클래스를 만들어서 스크롤이 항상 보이게 설정, 아니면 스크롤 생기면 왼쪽으로 밀려나는 현상 발생
    <html lang="en" className="alwaysScroll">
      <body className={inter.className}>
        <RQProvider>
          <AuthSession>
            <TopBar />
            <div style={{ width: "90%", maxWidth: "1600px", margin: "0 auto" }}>
              {/* 상단 바 */}
              {/* TopBar의 높이와 동일하게 설정 */}
              {/* 아래걸로 하면 전체스크롤 */}
              <div style={{ display: "flex", overflow: "hidden" }}>
                {/* <div style={{ display: "flex", height: "calc(100vh - 60px)", overflow: "hidden" }}> */}
                {/* 왼쪽 네비게이션 */}
                <NavMenuBar />
                {/* 메인 콘텐츠: 중앙 정렬 */}
                <div style={{ flexGrow: 1, paddingLeft: "3px", paddingRight: "3px", width: 1300, overflowY: "auto" }}>
                  {children}
                </div>
                <div style={{ width: "40%" }}>
                  <RightView />
                </div>
                {/* 전역 메세지 표시 설정 */}
                <MessageView />
              </div>
            </div>
          </AuthSession>
        </RQProvider>
      </body>
    </html>
  );
}
